FROM ubuntu:22.04 

USER root
WORKDIR /root

SHELL [ "/bin/bash", "-c" ]

ARG PYTHON_VERSION_TAG=3.11.4
ARG LINK_PYTHON_TO_PYTHON3=https://www.python.org/ftp/python

# Existing lsb_release causes issues with modern installations of Python3
# https://github.com/pypa/pip/issues/4924#issuecomment-435825490
# Set (temporarily) DEBIAN_FRONTEND to avoid interacting with tzdata
ENV TZ=Asia/Ho_Chi_Minh \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get -y install \
    build-essential \
    sudo \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev \
    libsqlite3-dev \
    wget \
    libbz2-dev \
    pkg-config \
    tk-dev \
    wget \
    curl \
    git \
    make \
    bash-completion \
    tree \
    vim \
    neofetch

RUN cd /usr/src \
    && sudo wget ${LINK_PYTHON_TO_PYTHON3}/${PYTHON_VERSION_TAG}/Python-${PYTHON_VERSION_TAG}.tgz \
    && sudo tar -xzf Python-${PYTHON_VERSION_TAG}.tgz \
    && cd Python-${PYTHON_VERSION_TAG} \
    && ./configure --enable-optimizations \
    && sudo make altinstall

# # Update the links to allow you to run python as opposed to specifying python3.11 when you want to run it.
RUN sudo update-alternatives --install /usr/bin/python python /usr/local/bin/python3.11 1
RUN sudo update-alternatives --install /usr/bin/pip pip /usr/local/bin/pip3.11 1

# Enable tab completion by uncommenting it from /etc/bash.bashrc
# The relevant lines are those below the phrase "enable bash completion in interactive shells"
RUN export SED_RANGE="$(($(sed -n '\|enable bash completion in interactive shells|=' /etc/bash.bashrc)+1)),$(($(sed -n '\|enable bash completion in interactive shells|=' /etc/bash.bashrc)+7))" && \
    sed -i -e "${SED_RANGE}"' s/^#//' /etc/bash.bashrc && \
    unset SED_RANGE

RUN apt install -y cinnamon locales

# Create user "docker" with sudo powers
RUN useradd -m docker && \
    usermod -aG sudo docker && \
    echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    cp /root/.bashrc /home/docker/ && \
    mkdir /home/docker/data && \
    chown -R --from=root docker /home/docker

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /home/docker/data
ENV HOME /home/docker
ENV USER docker
USER docker
ENV PATH /home/docker/.local/bin:$PATH
# Avoid first use of sudo warning. c.f. https://askubuntu.com/a/22614/781671
RUN touch $HOME/.sudo_as_admin_successful

CMD [ "/bin/bash" ]